#!/bin/sh
# Applications
~/.config/conky/start-conky.sh &
pidof redshift || redshift &
brave --class="init_brave" &

mpd_start &
pgrep bspswallow || bspswallow &

xautolock -detectsleep -time 10 -locker "~/.local/scripts/lock.sh" -notify 30 -notifier "notify-send -u critical -t 10000 -- 'LOCKING screen in 30 seconds'" &
